services:
  task_service_frontend2:
    build: .
    ports:
      - "4200:4200"
    container_name: task_service_frontend_container2
    volumes: # Volume binding
      - './:/usr/src/app'
    command: >
      bash -c "npm start"

